# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JsoLT9BSWS460ggpZBnFwZEBi0dVx-j
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os

#crear carpetas de destino
os.makedirs("salidas",exist_ok=True)
os.makedirs("dashboard",exist_ok=True)

#carga del archivo excel
df = pd.read_excel("dataset_set_A_aguas_residuales.xlsx")

#estructura y primeros registros
print("** Exploración inicial del dataset **")
print(f"\nDimensiones: {df.shape[0]} registros, {df.shape[1]} columnas")
print("\nPrimeras filas:")
print(df.head())
print("\nTipos de datos:")
print(df.dtypes)
print("\nEstadísticas descriptivas:")
print(df.describe().round(2))
print("\nValores nulos por columna:")
print(df.isnull().sum())
print("\nPlantas registradas:")
print(df["planta"].value_counts())

#conversion de fecha a tipo datetime para analisis temporal
df["fecha_registro"]=pd.to_datetime(df["fecha_registro"])

#calculo de eficiencia de remoción de DBO: indica qué porcentaje de contaminante fue removido por la planta
df["eficiencia_dbo_pct"] =((df["DBO_entrada_mg_L"] - df["DBO_salida_mg_L"]) / df["DBO_entrada_mg_L"]* 100).round(2)

#etiqueta de estado de cumplimiento legible
df["estado_cumplimiento"] = df["cumplimiento_norma"].map(
    {1: "Cumple", 0: "No cumple"}
)
print("\n ** Vista con columnas calculadas **")
print(df[["fecha_registro", "planta", "eficiencia_dbo_pct","estado_cumplimiento"]].head(10))

#analisis por planta
print("\n ** Métricas promedio por planta **")
resumen_plantas = df.groupby("planta").agg(
    registros=("fecha_registro", "count"),
    caudal_promedio=("caudal_entrada_m3_d","mean"),
    DBO_entrada_prom=("DBO_entrada_mg_L","mean"),
    DBO_salida_prom=("DBO_salida_mg_L","mean"),
    eficiencia_dbo_prom=("eficiencia_dbo_pct","mean"),
    energia_prom=("energia_aeracion_kWh","mean"),
    lodos_prom=("lodos_generados_kg_d","mean"),
    tasa_cumplimiento=("cumplimiento_norma","mean")
).round(2)

resumen_plantas["tasa_cumplimiento_pct"]=(resumen_plantas["tasa_cumplimiento"] * 100).round(1)
print(resumen_plantas)

#registros de incumplimiento por planta
print("\n ** Registros de incumplimiento por planta ** ")
incumplimientos = df[df["cumplimiento_norma"] == 0].groupby("planta").size()
print(incumplimientos)


#reporte para area de operaciones
cols_operaciones = [
    "fecha_registro", "planta", "caudal_entrada_m3_d",
    "DBO_entrada_mg_L", "DBO_salida_mg_L",
    "energia_aeracion_kWh", "lodos_generados_kg_d",
    "eficiencia_dbo_pct"
]
df_operaciones = df[cols_operaciones].copy()
df_operaciones = df_operaciones.sort_values(["planta", "fecha_registro"])
df_operaciones.to_excel("salidas/reporte_operaciones.xlsx", index=False)

#reporte para area de gestión ambiental
cols_ambiental =["fecha_registro", "planta","DBO_salida_mg_L","estado_cumplimiento","cumplimiento_norma"]
df_ambiental =df[cols_ambiental].copy()
df_ambiental =df_ambiental.sort_values(["planta","fecha_registro"])
df_ambiental.to_excel("salidas/reporte_gestion_ambiental.xlsx",index=False)

#dashboard exploratorio
colores = {
    "Planta Centro":"#4E6D8C",
    "Planta Norte":"#C87941",
    "Planta Sur":"#5A8A6A"
}
plantas = df["planta"].unique()

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle(
    "Dashboard Exploratorio AquaLimpia S.A.\n"
    "Desempeño de plantas de tratamiento de aguas residuales",
    fontsize=14, fontweight="bold", y=0.98
)

#grafico 1: DBO salida promedio por planta (barras)
ax1 = axes[0, 0]
dbo_prom = df.groupby("planta")["DBO_salida_mg_L"].mean().round(2)
bars1 = ax1.bar(
    dbo_prom.index, dbo_prom.values,
    color=[colores[p] for p in dbo_prom.index]
)
ax1.set_title("DBO de salida promedio por planta (mg/L)", fontsize=11)
ax1.set_ylabel("DBO salida (mg/L)")
ax1.set_xlabel("Planta")
for bar, val in zip(bars1, dbo_prom.values):
    ax1.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.3,
        f"{val:.1f}", ha="center", fontsize=9
    )

#grafico 2: tasa de cumplimiento normativo por planta (barras)
ax2 = axes[0, 1]
tasa = (df.groupby("planta")["cumplimiento_norma"].mean() * 100).round(1)
bars2 = ax2.bar(
    tasa.index, tasa.values,
    color=[colores[p] for p in tasa.index]
)
ax2.set_title("Tasa de cumplimiento normativo (%)", fontsize=11)
ax2.set_ylabel("Tasa cumplimiento (%)")
ax2.set_xlabel("Planta")
ax2.set_ylim(0, 50)
for bar, val in zip(bars2, tasa.values):
    ax2.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.5,
        f"{val}%", ha="center", fontsize=9
    )

#grafico 3: eficiencia de remoción DBO. boxplot por planta
ax3 = axes[1, 0]
data_box = [df[df["planta"] == p]["eficiencia_dbo_pct"].values for p in plantas]
bp = ax3.boxplot(data_box, tick_labels=plantas, patch_artist=True)
for patch, planta in zip(bp["boxes"], plantas):
    patch.set_facecolor(colores[planta])
    patch.set_alpha(0.7)
ax3.set_title("Eficiencia de remoción DBO por planta (%)", fontsize=11)
ax3.set_ylabel("Eficiencia remoción DBO (%)")
ax3.set_xlabel("Planta")

#grafico 4: dispersión caudal de entrada vs DBO de salida
ax4 = axes[1, 1]
for planta in plantas:
    sub = df[df["planta"] == planta]
    ax4.scatter(
        sub["caudal_entrada_m3_d"], sub["DBO_salida_mg_L"],
        color=colores[planta], label=planta, alpha=0.6, s=40
    )
ax4.set_title("Caudal de entrada vs DBO de salida",fontsize=11)
ax4.set_xlabel("Caudal entrada (m³/d)")
ax4.set_ylabel("DBO salida (mg/L)")
ax4.legend(fontsize=8)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig("dashboard/dashboard_aqualimpia.png", dpi=150, bbox_inches="tight")
plt.show()