# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JsoLT9BSWS460ggpZBnFwZEBi0dVx-j

# New Section
"""

import pandas as pd
import os
from funciones_aqualimpia import (
    calcular_indicadores_dbo,
    calcular_indicadores_caudal,
    tasa_incumplimiento,
    guardar_resultados,
    cargar_resultados
)

#carga del dataset
df = pd.read_excel("dataset_set_A_aguas_residuales.xlsx")

print("REPORTE MODULAR AQUALIMPIA S.A.")
print("Análisis por planta usando funciones reutilizables")

resultados_globales = {}

#analisis por planta usando las funciones del archivo externo
for planta in df["planta"].unique():

    sub = df[df["planta"] == planta]

    print(f"\n")
    print(f"{planta}")

    #eficiencia de remoción DBO con intervalo de confianza (NumPy + SciPy)
    ind_dbo = calcular_indicadores_dbo(
        sub["DBO_entrada_mg_L"].values,
        sub["DBO_salida_mg_L"].values
    )
    print(f"\nEficiencia de remoción DBO:")
    print(f"Promedio: {ind_dbo['eficiencia_promedio']} %")
    print(f"Desv. estándar: {ind_dbo['desviacion_estandar']} %")
    print(f"IC 95%: [{ind_dbo['ic95_inferior']} - {ind_dbo['ic95_superior']}] %")

    #estadisticas de caudal (NumPy)
    ind_caudal = calcular_indicadores_caudal(sub["caudal_entrada_m3_d"].values)
    print(f"\nCaudal de entrada (m³/d):")
    print(f"Media: {ind_caudal['media']}")
    print(f"Mediana: {ind_caudal['mediana']}")
    print(f"Desv. estándar: {ind_caudal['desviacion_estandar']}")
    print(f"Rango:{ind_caudal['minimo']} - {ind_caudal['maximo']}")

    #tasa de incumplimiento (NumPy)
    inc = tasa_incumplimiento(sub["cumplimiento_norma"].values)
    print(f"\nCumplimiento normativo:")
    print(f"Total registros:{inc['total_registros']}")
    print(f"Incumplimientos:{inc['incumplimientos']}")
    print(f"Tasa incumpl.:{inc['tasa_incumplimiento_pct']} %")

    #guardar resultados de esta planta
    resultados_globales[planta] = {
        "dbo": ind_dbo,
        "caudal": ind_caudal,
        "cumplimiento": inc
    }

print("\n")

#guardar todos los resultados con Joblib para reutilización futura
os.makedirs("../salidas", exist_ok=True)
guardar_resultados(resultados_globales, "../salidas/resultados_plantas.joblib")

#verificar que se pueden cargar correctamente
resultados_cargados = cargar_resultados("../salidas/resultados_plantas.joblib")

print("Verificación: resultados cargados correctamente")
print(f"Plantas disponibles: {list(resultados_cargados.keys())}")
print("\nReporte modular completado.")